services:
  - type: web
    name: kkphim-nuvio-addon
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /manifest.json
    autoDeployTrigger: commit
    renderSubdomainPolicy: enabled
