'use strict';
const assert=require('node:assert/strict');
const {parseListItems,parseDetail,collectSourceCandidates,itemType}=require('../hhtq_provider');
const base='https://hhhtq.team';
const list=`<div class="myui-vodlist__box"><a class="myui-vodlist__thumb" href="/phim/203/" title="Tiên Nghịch"><img data-original="/upload/tien-nghich.jpg"></a><span class="pic-text text-right">TẬP 153/180 VIETSUB</span></div>`;
const items=parseListItems(list,base);
assert.equal(items.length,1);
assert.equal(items[0].title,'Tiên Nghịch');
assert.match(items[0].posterUrl,/tien-nghich/);
const detail=`<meta property="og:title" content="Tiên Nghịch | HHTQ"><meta property="og:image" content="/poster.jpg"><meta name="description" content="Mô tả"><h1>Tiên Nghịch</h1><div id="playlist1"><a href="/xem/203/tap-1/">Tập 1</a><a href="/xem/203/tap-2/">Tập 2</a></div>`;
const d=parseDetail(detail,'https://hhhtq.team/phim/203/',base);
assert.equal(d.episodes.length,2);
assert.equal(d.episodes[1].number,2);
const watch=`<div id="player1"><a class="episode-link" href="https://vip.cliphub.tv/embed/vabc123">Cliphub #1</a></div><div id="links-backup"><a data-play="api" href="https://rumble.com/embed/v9xyz/">Rumble</a></div><script>var p={file:"https://cdn.example.com/master.m3u8"}</script>`;
const links=collectSourceCandidates(watch,'https://hhhtq.team/xem/203/tap-1/',base);
assert.ok(links.some(x=>x.url.includes('cliphub')));
assert.ok(links.some(x=>x.url.includes('rumble')));
assert.ok(links.some(x=>x.url.includes('master.m3u8')));
assert.equal(itemType('[Movie] Bạch Xà','FULL','/phim/1/'),'movie');
console.log('hhtq provider fixture tests PASS');
